config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  devise_for :users, path: "auth", path_names: { sign_in: 'sign_in', sign_out: 'sign_out', password: 'password', confirmation: 'verification', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :todos do
  	member do
  		put :complete
  		put :undo
  	end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      cannot :manage, :all
      
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :user
	#validates :name, presence: true, length: { minimum: 2 }

	def toggle_completion!
		update_attribute(:completed, true)
	end

	def undo_completion!
		update_attribute(:completed, false)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos
  has_many :user_roles

  before_create :downcase_name, :downcase_email

  def to_param
    name
  end

  def downcase_name
    self.name = name.downcase
  end

  def downcase_email
    self.email = email.downcase
  end

  def admin?
    self.has_role? :admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :set_todo, only: [:edit, :update, :destroy, :complete, :undo]
	before_filter :authenticate_user!
	
	def index
		@todos = Todo.where(completed: false).all
		@dones = Todo.where(completed: true).all
	end

	def new
		@todo = current_user.todos.new
	end

	def edit
		if !current_user.admin?
			redirect_to todos_path, alert: "You don't have permission to do that."
		end
	end

	def create
		@todo = current_user.todos.new(todo_params)

		respond_to do |format|
			if @todo.save && current_user.admin?
				format.html { redirect_to todos_path, notice: "Task was sucessfully created"}
				format.js { }
			else
				format.html { render :new }
				format.js { }
			end
		end
	end

	def update
		if current_user.admin?
			respond_to do |format|
		      if @todo.update(todo_params) && current_user.admin?
		        format.html { redirect_to todos_path, notice: 'Task was successfully updated.' }
		        format.js { }
		      else
		        format.html { render :edit }
		        format.js { }
		      end
		    end
		else
			redirect_to todos_path, alert: "You don't have permission to do that."
		end
	end

	def destroy
		if current_user.admin?
			respond_to do |format|
				if @todo.destroy
		    		format.html { redirect_to todos_path, notice: 'Task was successfully destroyed.' }
		    		format.js { }
		    	else
		    		format.html { redirect_to todos_path, alert: 'Something went worng.' }
		    		format.js { }
		    	end
		    end
		else
			redirect_to todos_path, alert: "You don't have permission to do that."
		end
	end

	def complete
		#@dones = Todo.where(completed: true).all
		@todo.toggle_completion!
		@done = @todo
		respond_to do |format|
			format.html { redirect_to todos_path, notice: "Yay!" }
			format.js {  }
		end
	end

	def undo
		@todo.undo_completion!
		
		respond_to do |format|
			format.html { redirect_to todos_path, notice: "Oh, let's put it back." }
			format.js
		end
	end

	private

	def ensure_admin
		if current_user.admin?
			true
		else
			false
		end
	end

	def todo_params
		params[:todo].permit(:name)
	end

	def set_todo
		@todo = Todo.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		redirect_to todos_path and return if user_signed_in?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
	<div data-alert class="flash alert-box text-center <%= type %>">
		<%= message %>
		<a href="#" class="close">&times;</a>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="small-6 columns clearfix">
      <a href="https://github.com/alexbtlv/todo"><i class="fa fa-github fa-2x right"></i></a>
    </div>
    <div class="small-6 columns clearfix">
        <a href="https://twitter.com/Alexbtlv"><i class="fa fa-twitter fa-2x left"></i></a>
    </div>
  </div>
  <div class="row">
    <div class="small-12 column">
      <h5 class="text-center"><small>A simple Rails TODO app. An entry for <a href="http://codecademy.com/">CodeCademy</a> coding challenge by <a href="http://teamtreehouse.com/alexanderbatalov">Alexander Batalov.</a></small></h5>
    </div>
  </div>  
</footer>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-26994640-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_navbar.html.erb
<div class="row">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "TODO", root_path %></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if user_signed_in? %>
        <li></li>
        <li class="has-dropdown">
          <a href="#"><i class="fa fa-lg"><%= current_user.name.split.map(&:capitalize)*' ' %></i></a>
          <ul class="dropdown list-group">
            <li><%= link_to content_tag(:i, "Sign Out", :class => "fa fa-sign-out fa-lg"), destroy_user_session_path,  method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to content_tag(:i,"Sign Up", :class=>"fa fa-users fa-lg"), new_user_registration_path %>
        </li>
        <li>
          <%= link_to content_tag(:i,"Sign In", :class=>"fa fa-sign-in fa-lg"), new_user_session_path %>
        </li>
        <% end %>
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to  content_tag(:i, '',:class => "fa fa-plus fa-lg"), new_todo_path, id: "new_link",remote: true %></li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "todo-codecademy" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div id="wrapper" class="row">
      <div class="small-12 small-centered medium-8 medium-centered large-6 large-centered column">
        <% if controller_name == 'todos' %>
          <%= render partial: "layouts/navbar" %>
        <% end %>
        <%= render partial: "layouts/flash" %>
        <div id="new_form"></div>
        <div id="content">
          <%= yield %>
        </div>
      </div>
      <%= render partial: "layouts/footer" %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/todos/_done.html.erb
<div class="row" id="<%= dom_id(done) %>">
	<div class="small-10 column">
		<h6><%= content_tag(:i, done.name.capitalize, :class=>"fa fa-check-square-o fa-lg") %></h6>
	</div>
	<% if current_user.admin? %>
		<div class="small-1 column">
			<%= link_to undo_todo_path(done), method: :put, remote: true  do %>
			<span title="Undo">
				<%= content_tag(:i, '', :class => "fa fa-undo fa-lg" ) %>
			</span>
			<% end %>
		</div>
		<div class="small-1 column">
			<%= link_to done, method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
				<span title="Delete">
					<%= content_tag(:i, '', :class => "fa fa-trash-o fa-lg") %>
				</span>
			<% end %>
		</div>
	<% else %>
		<div class="small-2 column clearfix">
			<%= link_to undo_todo_path(done), method: :put, remote: true  do %>
			<span class="right" title="Undo">
				<%= content_tag(:i, '', :class => "fa fa-undo fa-lg" ) %>
			</span>
			<% end %>
		</div>
	<% end %>
	<hr />
</div>

app/views/todos/_dones.html.erb
<% @dones.each do |done| %>
<div class="row" id="<%= dom_id(done) %>">
	<div class="small-10 column">
		<h6><%= content_tag(:i, done.name.capitalize, :class=>"fa fa-check-square-o fa-lg") %></h6>
	</div>
	<% if current_user.admin? %>
		<div class="small-1 column">
			<%= link_to undo_todo_path(done), method: :put, remote: true  do %>
			<span title="Undo">
				<%= content_tag(:i, '', :class => "fa fa-undo fa-lg" ) %>
			</span>
			<% end %>
		</div>
		<div class="small-1 column">
			<%= link_to done, method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
				<span title="Delete">
					<%= content_tag(:i, '', :class => "fa fa-trash-o fa-lg") %>
				</span>
			<% end %>
		</div>
	<% else %>
		<div class="small-2 column clearfix">
			<%= link_to undo_todo_path(done), method: :put, remote: true  do %>
			<span class="right" title="Undo">
				<%= content_tag(:i, '', :class => "fa fa-undo fa-lg" ) %>
			</span>
			<% end %>
		</div>
	<% end %>
	<hr />
</div>
<% end %>

app/views/todos/_form.html.erb
<div id="form">
<%= form_for @todo, remote: true do |f| %>
	<div class="row collapse">
		<div class="small-1 column">
			<%= f.label "todo:", :class => "left inline" %>
		</div>
		<div class="small-7 column">
			<%= f.text_field :name, :id => "right-label", autofocus: true %>
		</div>
		<div class="small-2 column">
			<%= f.submit "Save", class: "button postfix" %>
		</div>
		<div class="small-2 column" id="closer">
			<a href="#" class="button postfix secondary">Close</a>
		</div>
	</div>
<% end %>
</div>

app/views/todos/_todo.html.erb
<div class="row" id="edit_form_<%= dom_id(todo) %>"></div>
<div class="row todos" id="<%= dom_id(todo) %>">
	<div class="small-10 column">
		<h6><%= content_tag(:i, todo.name.capitalize, :class=>"fa fa-hand-o-right fa-lg")%></h6>
	</div>
	<% if current_user.admin? %>
		<div class="small-1 column">
			<%= link_to edit_todo_path(todo), remote: true do %>
				<span title="Edit">
					<%= content_tag(:i, '', :class => "fa fa-cog fa-lg") %>
				</span>
			<% end %>
		</div>
		
		<div class="small-1 column">
			<%= link_to complete_todo_path(todo), method: :put, remote: true do %>
				<span title="Mark as completed!">
					<%= content_tag(:i, '', :class => "fa fa-check-square-o fa-lg") %>
				</span>
			<% end %>
		</div>
	<% else %>
		<div class="small-2 column clearfix">
			<%= link_to complete_todo_path(todo), method: :put, remote: true do %>
				<span class="right" title="Mark as completed!">
					<%= content_tag(:i, '', :class => "fa fa-check-square-o fa-lg") %>
				</span>
			<% end %>
		</div>
	<% end %>
	<hr />
</div>

app/views/todos/complete.js.erb
$('#todo_<%= @todo.id %>').remove();
$('#dones').append("<%= j render partial: 'done', locals: { done: @done} %>");

app/views/todos/create.js.erb
$('.new_todo').remove();
$('#new_link').show();
$('#todo').append('<%= j render(@todo) %>');

app/views/todos/destroy.js.erb
$('#todo_<%= @todo.id %>').remove();

app/views/todos/edit.js.erb
$('.todos #todo_<%= @todo.id %>').remove();
$('#edit_form_todo_<%= @todo.id %>').show();
$('#edit_form_todo_<%= @todo.id %>').append("<%= j render partial: 'form' %>");
$("#closer").click(function(){
	$("#form").slideUp('fast');
	$('#todo').append('<%= j render(@todo) %>');
});

app/views/todos/index.html.erb
<div id="todo">
	<%= render @todos %>
</div>
<div id="dones">
	<%= render partial: 'dones', locals: { dones: @dones } %>
</div>

app/views/todos/new.js.erb
$('#new_link').hide();
$('#new_form').slideDown('fast').after('<%= j render("form") %>');
$("#closer").click(function(){
	$('#form').slideUp('fast');
	$('#new_link').show();
});

app/views/todos/undo.js.erb
$('#todo_<%= @todo.id %>').remove();
$('#todo').append('<%= j render(@todo) %>')

app/views/todos/update.js.erb
$('#edit_form_todo_<%= @todo.id %>').remove();
$('#todo').append('<%= j render(@todo) %>');

app/views/welcome/home.html.erb
<div class="row">
	<div class="small-12 column">
		<h2 class="text-center">Hey, Welcome!</h2>
		<p class="text-center">This is a simple todo rails app for CodeCademy coding challenge by Alexander Batalov</p>
	</div>
	<hr />
	<div class="small-6 column">
		<%= link_to "Sign Up", new_user_registration_path, class: "button radius expand" %>
	</div>
	<div class="small-6 column">
		<%= link_to "Sign In", new_user_session_path,  class: "button secondary radius expand" %>
	</div>
	<div class="small-12">
		<p class="text-center" style="color:red">Notice: This app is for demostration purposes only. Regular users can only create and complete TODO items. To be able update or delete TODO's user should have admin rights.</p>
	</div>
</div>